In [63]:
import numpy as np
import torch
from torch import nn
from tropical import to_tensor, Tropical, TropicalMonomial, TropicalPolynomial, PolyNet, DiffPolyNet

In [64]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [65]:
x = np.random.randint(20,size=3)
x_t = to_tensor(x)

Создадим тестовые полиномы

In [66]:
a = TropicalPolynomial([[1.2345,3,2,1],[1.2345,2,7,1],[1.2345,0,9,1],
                        [1.2345,10,19,1]])

b = TropicalPolynomial([[1.2345,2,3,1],[2.3456,3,4,1]])

In [67]:
a.evaluate(x), b.evaluate(x)

(124.2345, 37.345600000000005)

Создадим сетку для каждого полинома

In [68]:
a_net = PolyNet(a)
b_net = PolyNet(b)

In [69]:
a_net

PolyNet(
  (net): Sequential(
    (0): Linear(in_features=3, out_features=6, bias=True)
    (1): ReLU()
    (2): Linear(in_features=6, out_features=3, bias=True)
    (3): ReLU()
    (4): Linear(in_features=3, out_features=1, bias=True)
  )
)

In [70]:
a_net.forward(x_t)

tensor([124.2345], grad_fn=<AddBackward0>)

In [71]:
b_net

PolyNet(
  (net): Sequential(
    (0): Linear(in_features=3, out_features=3, bias=True)
    (1): ReLU()
    (2): Linear(in_features=3, out_features=1, bias=True)
  )
)

In [72]:
b_net.forward(x_t)

tensor([37.3456], grad_fn=<AddBackward0>)

Значения сошлись!

Посмотрим на разность этих полиномов

In [73]:
a.evaluate(x)/b.evaluate(x)

86.88889999999999

In [74]:
a_net.forward(x_t)-b_net.forward(x_t)

tensor([86.8889], grad_fn=<SubBackward0>)

Создадим сетку для разности

In [75]:
net = DiffPolyNet(a,b)

In [76]:
net

DiffPolyNet(
  (net): Sequential(
    (0): Linear(in_features=6, out_features=9, bias=True)
    (1): ReLU()
    (2): Linear(in_features=9, out_features=4, bias=True)
    (3): ReLU()
    (4): Linear(in_features=4, out_features=1, bias=True)
  )
)

In [77]:
net.forward(x_t)

tensor([86.8889], grad_fn=<AddBackward0>)

Тоже сошлось!

Для уверенности поменяем полиномы местами, теперь получится отрицательное значение разности

In [188]:
a = TropicalPolynomial([[1.2345,2,3,1],[2.3456,3,4,1]])


b = TropicalPolynomial([[1.2345,3,2,1],[1.2345,2,7,1],[1.2345,0,9,1],
                        [1.2345,10,19,1]])

In [189]:
a_net = PolyNet(a)
b_net = PolyNet(b)

In [190]:
a.evaluate(x), b.evaluate(x)

(37.345600000000005, 124.2345)

In [191]:
a_net.forward(x_t), b_net.forward(x_t)

(tensor([37.3456], grad_fn=<AddBackward0>),
 tensor([124.2345], grad_fn=<AddBackward0>))

In [192]:
a.evaluate(x)/b.evaluate(x)

-86.88889999999999

In [193]:
a_net.forward(x_t)-b_net.forward(x_t)

tensor([-86.8889], grad_fn=<SubBackward0>)

In [194]:
net = DiffPolyNet(a,b)

In [195]:
net.forward(x_t)

tensor([-86.8889], grad_fn=<AddBackward0>)